language: python
# Use containers instead of VMs
sudo: false

os:
    - linux
    - osx

addons:
    apt:
        packages:
        - libnss3

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nss ; fi

script:
    - cd tests && ./run_all -v
